# Generated by Django 5.2.13 on 2026-04-10 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cells', '0001_initial'),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(verbose_name='Endereço')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='cells.cell', verbose_name='Célula')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_locations', to='hosts.host', verbose_name='Anfitrião')),
            ],
            options={
                'verbose_name': 'Local de Célula',
                'verbose_name_plural': 'Locais de Células',
                'db_table': 'cell_location',
                'ordering': ['-is_active', 'cell__name'],
                'indexes': [models.Index(fields=['cell', 'is_active'], name='cell_locati_cell_id_f6e4d1_idx'), models.Index(fields=['host'], name='cell_locati_host_id_262fe0_idx')],
            },
        ),
    ]
