# Generated by Django 5.2.13 on 2026-04-10 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_types', '0003_alter_eventtype_description_alter_eventtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateField(db_index=True, unique=True, verbose_name='Data do Evento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_events', to='event_types.eventtype', verbose_name='Tipo de Evento')),
            ],
            options={
                'verbose_name': 'Evento do Calendário',
                'verbose_name_plural': 'Eventos do Calendário',
                'db_table': 'calendar_event',
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['event_date'], name='calendar_ev_event_d_6c6895_idx'), models.Index(fields=['event_type'], name='calendar_ev_event_t_328d58_idx')],
            },
        ),
    ]
