# Generated by Django 5.2.13 on 2026-04-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
    ]
