# Generated by Django 5.2.13 on 2026-04-09 22:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('RED', 'Vermelha'), ('YELLOW', 'Amarela'), ('BLUE', 'Azul'), ('GREEN', 'Verde'), ('WHITE', 'Branca')], max_length=20, unique=True)),
                ('is_mag', models.BooleanField(default=False, help_text='Marque se for a área MAG (Área Vermelha)')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'area',
                'ordering': ['color'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('color', 'RED'), ('is_mag', True)), ('is_mag', False), _connector='OR'), name='mag_area_must_be_red')],
            },
        ),
    ]
