# Generated by Django 5.2.13 on 2026-04-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ["color"],
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
            },
        ),
    ]
