# Generated by Django 5.2.13 on 2026-04-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(choices=[('CELULA', 'Célula'), ('LIVRE', 'Livre'), ('MAG', 'Mag')], max_length=10, unique=True),
        ),
    ]
