# Generated by Django 5.2.13 on 2026-04-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0002_alter_eventtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(choices=[('CELULA', 'Célula'), ('LIVRE', 'Livre'), ('MAG', 'Mag')], max_length=10, unique=True, verbose_name='Nome'),
        ),
    ]
