# Generated by Django 5.2.13 on 2026-04-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_types", "0003_alter_eventtype_description_alter_eventtype_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Tipo de Evento",
                "verbose_name_plural": "Tipos de Eventos",
            },
        ),
        migrations.AlterModelTable(
            name="eventtype",
            table="event_type",
        ),
    ]
