# Generated by Django 5.2.13 on 2026-04-09 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(choices=[('PASTOR', 'Pastor'), ('SUPERVISOR_AREA', 'Supervisor de Área'), ('SUPERVISOR_CELULA', 'Supervisor de Célula'), ('FACILITADOR', 'Facilitador'), ('AUXILIAR', 'Auxiliar')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hierarchy_level', models.IntegerField(editable=False, help_text='Definido automaticamente baseado no cargo')),
            ],
            options={
                'db_table': 'leadership_role',
                'ordering': ['hierarchy_level'],
            },
        ),
    ]
