# Generated by Django 5.2.13 on 2026-04-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leadership_roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leadershiprole",
            options={
                "ordering": ["hierarchy_level"],
                "verbose_name": "Cargo de Liderança",
                "verbose_name_plural": "Cargos de Liderança",
            },
        ),
    ]
