# Generated by Django 5.2.13 on 2026-04-10 21:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_address', models.TextField(verbose_name='Endereço Completo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_locations', to='person.person', verbose_name='Anfitrião')),
            ],
            options={
                'verbose_name': 'Local de Anfitrião',
                'verbose_name_plural': 'Locais de Anfitriões',
                'db_table': 'host',
                'ordering': ['person__full_name'],
                'indexes': [models.Index(fields=['person'], name='host_person__3782e2_idx')],
            },
        ),
    ]
