# Generated by Django 5.2.13 on 2026-04-11 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_events', '0001_initial'),
        ('cell_locations', '0001_initial'),
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_date', models.DateField(db_index=True, verbose_name='Data da Reunião')),
                ('took_place', models.BooleanField(default=True, verbose_name='Realizada')),
                ('total_attendees', models.PositiveIntegerField(default=0, verbose_name='Total de Presentes')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_meetings', to='calendar_events.calendarevent', verbose_name='Evento no Calendário')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='cells.cell', verbose_name='Célula')),
                ('cell_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='cell_locations.celllocation', verbose_name='Local da Célula')),
            ],
            options={
                'verbose_name': 'Reunião de Célula',
                'verbose_name_plural': 'Reuniões de Células',
                'db_table': 'cell_meeting',
                'ordering': ['-meeting_date', 'cell__name'],
                'indexes': [models.Index(fields=['cell', 'meeting_date'], name='cell_meetin_cell_id_e5501c_idx'), models.Index(fields=['meeting_date'], name='cell_meetin_meeting_428232_idx'), models.Index(fields=['took_place'], name='cell_meetin_took_pl_a9bc63_idx'), models.Index(fields=['cell', 'took_place'], name='cell_meetin_cell_id_743d5c_idx')],
                'constraints': [models.UniqueConstraint(fields=('cell', 'meeting_date'), name='unique_cell_meeting_per_day')],
            },
        ),
    ]
