# Generated by Django 5.2.13 on 2026-04-10 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('cells', '0001_initial'),
        ('leadership_roles', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='areas.area', verbose_name='Área')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='cells.cell', verbose_name='Célula')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_positions', to='person.person', verbose_name='Pessoa')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='leadership_roles.leadershiprole', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Liderança',
                'verbose_name_plural': 'Lideranças',
                'db_table': 'leadership',
                'ordering': ['-is_active', 'role__hierarchy_level', 'start_date'],
                'indexes': [models.Index(fields=['person', 'is_active'], name='leadership_person__de1cb1_idx'), models.Index(fields=['role', 'is_active'], name='leadership_role_id_deb341_idx'), models.Index(fields=['area', 'is_active'], name='leadership_area_id_21e241_idx'), models.Index(fields=['cell', 'is_active'], name='leadership_cell_id_cc872f_idx')],
            },
        ),
    ]
