# Generated by Django 5.2.13 on 2026-04-11 01:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cells', '0001_initial'),
        ('leadership_roles', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cells.cell', verbose_name='Célula')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_memberships', to='members.member', verbose_name='Membro')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cell_members', to='leadership_roles.leadershiprole', verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Membro de Célula',
                'verbose_name_plural': 'Membros de Células',
                'db_table': 'cell_member',
                'ordering': ['cell__name', '-is_active', 'member__person__full_name'],
                'indexes': [models.Index(fields=['member', 'cell', 'is_active'], name='cell_member_member__93d027_idx'), models.Index(fields=['cell', 'is_active'], name='cell_member_cell_id_c76014_idx'), models.Index(fields=['role'], name='cell_member_role_id_10147d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('member', 'cell', 'role'), name='unique_active_member_cell_role')],
            },
        ),
    ]
