# Generated by Django 5.2.13 on 2026-04-16 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cell_members", "0001_initial"),
        ("cells", "0002_cell_cell_area_id_521525_idx_and_more"),
        ("leadership_roles", "0002_alter_leadershiprole_options"),
        ("members", "0002_member_member_person__2c8419_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cellmember",
            name="unique_active_member_cell_role",
        ),
        migrations.AlterField(
            model_name="cellmember",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional. Preencha apenas se o membro tiver função de liderança nesta célula.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cell_members",
                to="leadership_roles.leadershiprole",
                verbose_name="Função de Liderança",
            ),
        ),
        migrations.AddConstraint(
            model_name="cellmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("member", "cell"),
                name="unique_active_member_cell",
            ),
        ),
    ]
