# Generated by Django 5.2.13 on 2026-04-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ministries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ministry",
            options={
                "ordering": ["name"],
                "verbose_name": "Ministério",
                "verbose_name_plural": "Ministérios",
            },
        ),
    ]
