# Generated by Django 5.2.13 on 2026-04-11 02:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMinistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministries', to='members.member', verbose_name='Membro')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ministries.ministry', verbose_name='Ministério')),
            ],
            options={
                'verbose_name': 'Membro de Ministério',
                'verbose_name_plural': 'Membros de Ministérios',
                'db_table': 'member_ministry',
                'ordering': ['-is_active', 'member__person__full_name', 'ministry__name'],
                'indexes': [models.Index(fields=['member', 'is_active'], name='member_mini_member__3914ec_idx'), models.Index(fields=['ministry', 'is_active'], name='member_mini_ministr_05b3c1_idx'), models.Index(fields=['start_date'], name='member_mini_start_d_f6d630_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('member', 'ministry'), name='unique_active_member_ministry')],
            },
        ),
    ]
