# Generated by Django 5.2.13 on 2026-04-10 19:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name='Nome Completo')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Gênero')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Solteiro(a)'), ('MARRIED', 'Casado(a)'), ('WIDOWED', 'Viúvo(a)'), ('SEPARATED', 'Separado(a)')], max_length=20, verbose_name='Estado Civil')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Telefone')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'person',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='person_full_na_058eac_idx'), models.Index(fields=['phone'], name='person_phone_e491f7_idx')],
            },
        ),
    ]
