# Generated by Django 5.2.13 on 2026-04-11 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cell_meetings', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField(db_index=True, default=False, verbose_name='Presente')),
                ('absence_reason', models.TextField(blank=True, verbose_name='Motivo da Ausência')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('cell_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='cell_meetings.cellmeeting', verbose_name='Reunião')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Presença em Reunião',
                'verbose_name_plural': 'Presenças em Reuniões',
                'db_table': 'meeting_attendance',
                'ordering': ['-cell_meeting__meeting_date', 'member__person__full_name'],
                'indexes': [models.Index(fields=['cell_meeting', 'attended'], name='meeting_att_cell_me_184494_idx'), models.Index(fields=['member', 'attended'], name='meeting_att_member__a5c283_idx'), models.Index(fields=['attended'], name='meeting_att_attende_e2852e_idx')],
                'constraints': [models.UniqueConstraint(fields=('cell_meeting', 'member'), name='unique_attendance_per_meeting')],
            },
        ),
    ]
