# Generated by Django 5.2.13 on 2026-04-10 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('mag_branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome')),
                ('cgsbc', models.CharField(blank=True, help_text='Church name for non-MAG cells', max_length=100, verbose_name='CGSBC')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cells', to='areas.area', verbose_name='Área')),
                ('mag_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cells', to='mag_branches.magbranch', verbose_name='Ramificação MAG')),
            ],
            options={
                'verbose_name': 'Célula',
                'verbose_name_plural': 'Células',
                'db_table': 'cell',
                'ordering': ['name'],
            },
        ),
    ]
