# Generated by Django 5.2.13 on 2026-04-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0002_alter_area_options"),
        ("cells", "0001_initial"),
        ("mag_branches", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cell",
            index=models.Index(fields=["area"], name="cell_area_id_521525_idx"),
        ),
        migrations.AddIndex(
            model_name="cell",
            index=models.Index(fields=["mag_branch"], name="cell_mag_bra_c4c3b2_idx"),
        ),
    ]
