# Generated by Django 5.2.13 on 2026-04-09 22:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('A2', 'A2'), ('OW', 'OW'), ('MAG', 'MAG')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'MAG Branch',
                'verbose_name_plural': 'MAG Branches',
                'db_table': 'mag_branch',
                'ordering': ['name'],
            },
        ),
    ]
