# Generated by Django 5.2.13 on 2026-04-10 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cells', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField(db_index=True, verbose_name='Data da Visita')),
                ('became_member', models.BooleanField(default=False, verbose_name='Tornou-se Membro')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='cells.cell', verbose_name='Célula')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='person.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitor',
                'ordering': ['-visit_date', 'person__full_name'],
                'indexes': [models.Index(fields=['person', 'cell'], name='visitor_person__1e6757_idx'), models.Index(fields=['became_member'], name='visitor_became__08a550_idx')],
            },
        ),
    ]
