# Generated by Django 5.2.13 on 2026-04-11 02:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cells', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano')),
                ('month', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês')),
                ('total_meetings', models.PositiveIntegerField(default=0, verbose_name='Total de Reuniões')),
                ('attendances', models.PositiveIntegerField(default=0, verbose_name='Presenças')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percentual de Presença')),
                ('is_faithful', models.BooleanField(db_index=True, default=False, verbose_name='Fiel')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendances', to='cells.cell', verbose_name='Célula')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendances', to='members.member', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Frequência Mensal',
                'verbose_name_plural': 'Frequências Mensais',
                'db_table': 'monthly_attendance',
                'ordering': ['-year', '-month', '-attendance_percentage', 'member__person__full_name'],
                'indexes': [models.Index(fields=['member', 'year', 'month'], name='monthly_att_member__92e636_idx'), models.Index(fields=['cell', 'year', 'month'], name='monthly_att_cell_id_757b4b_idx'), models.Index(fields=['year', 'month'], name='monthly_att_year_acaa5d_idx'), models.Index(fields=['is_faithful', 'year', 'month'], name='monthly_att_is_fait_a0e138_idx'), models.Index(fields=['attendance_percentage'], name='monthly_att_attenda_238eed_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'cell', 'year', 'month'), name='unique_monthly_attendance'), models.CheckConstraint(condition=models.Q(('attendances__lte', models.F('total_meetings'))), name='attendances_cannot_exceed_total_meetings'), models.CheckConstraint(condition=models.Q(('attendance_percentage__gte', 0.0), ('attendance_percentage__lte', 100.0)), name='attendance_percentage_range')],
            },
        ),
    ]
