# Generated by Django 5.2.13 on 2026-04-10 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('entry_date', models.DateField(verbose_name='Data de Entrada')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to='person.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'db_table': 'member',
                'ordering': ['person__full_name'],
            },
        ),
    ]
