# Generated by Django 5.2.13 on 2026-04-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["person"], name="member_person__2c8419_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["is_active"], name="member_is_acti_1d4be6_idx"),
        ),
    ]
